# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
#FROM registry.access.redhat.com/ubi8/ubi:8.0


MAINTAINER Red Hat Training <training@redhat.com>

# DocumentRoot for Apache
#ENV DOCROOT=/var/www/html 


#RUN   yum install -y --nodocs --disableplugin=subscription-manager httpd && \
#      yum clean all --disableplugin=subscription-manager -y && \
#      echo "Hello from the httpd-parent container!" > ${DOCROOT}/index.html

# Allows child images to inject their own content into DocumentRoot
#ONBUILD COPY src/ ${DOCROOT}/

EXPOSE 8080
LABEL io.k8s.description="HTTP Child image, uses ONBUILD" \ 
      io.k8s.display-name="Apache HTTP server" \ 
      io.openshift.expose-service="8080:http" \
      io.openshift.tags="apache, httpd"
RUN sed -i "s/LISTEN 80/LISTEN 8080/g" /etc/httpd/conf/httpd.conf
RUN chgrp -R 0 /var/log/httpd/ /var/run/httpd && \
    chmod -R g=u /var/log/httpd/ /var/run/httpd 
# This stuff is needed to ensure a clean start
#RUN rm -rf /run/httpd && mkdir /run/httpd

# Run as the root user
USER 1001

# Launch httpd
#CMD /usr/sbin/httpd -DFOREGROUND
